{
    shop = {
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Душа", buyPrice = 15000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id=""}}, raw_name = {"item."}},
		{text = "Слиток Меди", buyPrice = 75, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotcopper"}},
		{text = "Слиток Олова", buyPrice = 75, minCount = 0, maxCount = 15000, fingerprint = {{dmg=1.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemtingottin"}},
		{text = "МФЭ", buyPrice = 10000, minCount = 0, maxCount = 1500, fingerprint = {{dmg=1.0,id="IC2:blockElectric"}}, raw_name = {"ic2.blockmfe"}},
		{text = "Генератор", buyPrice = 1000, minCount = 0, maxCount = 5000, fingerprint = {{dmg=0.0,id="IC2:blockGenerator"}}, raw_name = {"ic2.blockgenerator"}},
		{text = "Металлоформировачный мех.", buyPrice = 2500, minCount = 0, maxCount = 5000, fingerprint = {{dmg=4.0,id="IC2:blockMachine2"}}, raw_name = {"ic2.blockmetalformer"}},
		{text = "Алмазная кирка", buyPrice = 1500, minCount = 0, maxCount = 1500, fingerprint = {{dmg=0.0,id="minecraft:diamond_pickaxe"}}, raw_name = {"item.pickaxediamond"}},
		{text = "Генератор материи", buyPrice = 10000, minCount = 0, maxCount = 1500, fingerprint = {{dmg=14.0,id="IC2:blockMachine"}}, raw_name = {"ic2.blockmatter"}},
		{text = "Энерго Ядро Виверны", buyPrice = 80000, minCount = 0, maxCount = 1500, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconiumEnergyCore"}}, raw_name = {"item.draconicevolution:draconiumenergycore0"}},
		{text = "Звезда Ада", buyPrice = 2250000, minCount = 0, maxCount = 1500, fingerprint = {{dmg=0.0,id="minecraft:nether_star"}}, raw_name = {"item.netherstar"}},
		{text = "Динамитная шашка", buyPrice = 1500, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id="AdditionMod:ItemBoomBoom"}}, raw_name = {"item.boomboom"}},
		{text = "Капсула с материей", buyPrice = 150000, minCount = 0, maxCount = 50000, fingerprint = {{dmg=3.0,id="IC2:itemCellEmpty"}}, raw_name = {"ic2.itemcelluumatter"}},
		{text = "Обсидиановая пыль", buyPrice = 750, minCount = 0, maxCount = 50000, fingerprint = {{dmg=11.0,id="IC2:itemDust"}}, raw_name = {"ic2.itemdustobsidian", "item.thermalfoundation.material.dustobsidian"}},
		{text = "Обсидиан", buyPrice = 1000, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:obsidian"}}, raw_name = {"item.obsidian"}},
		{text = "Стекло", buyPrice = 15, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:glass"}}, raw_name = {"item.glass"}},
		{text = "Слиток иридия", buyPrice = 30000, minCount = 0, maxCount = 15000, fingerprint = {{dmg=10.0,id="AdvancedSolarPanel:asp_crafting_items"}}, raw_name = {"ingotiridium"}},
		{text = "Улучшение Энергохранитель", buyPrice = 1500, minCount = 0, maxCount = 5000, fingerprint = {{dmg=2.0,id="IC2:upgradeModule"}}, raw_name = {"ic2.energystorageupgrade"}},
		{text = "Улучшение Выталкиватель", buyPrice = 1500, minCount = 0, maxCount = 5000, fingerprint = {{dmg=3.0,id="IC2:upgradeModule"}}, raw_name = {"ic2.ejectorupgrade"}},
		{text = "Заряженный драк. блок", buyPrice = 20000, minCount = 0, maxCount = 5000, fingerprint = {{dmg=2.0,id="DraconicEvolution:draconium"}}, raw_name = {"item.draconicEvolution:draconium"}},
		{text = "Пробужденный драк. слиток", buyPrice = 350000, minCount = 0, maxCount = 5000, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconicIngot"}}, raw_name = {"item.draconicEvolution:draconicingot"}},
		{text = "Укрепленный камень", buyPrice = 5000, minCount = 0, maxCount = 5000, fingerprint = {{dmg=0.0,id="IC2:blockAlloy"}}, raw_name = {"ic2.blockalloy"}},
		{text = "Пустой шаблон", buyPrice = 1500, minCount = 0, maxCount = 5000, fingerprint = {{dmg=52.0,id="appliedenergestics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergestics2.itemmaterial.blankpattern"}},
		{text = "Компонент хранения на 1К", buyPrice = 500, minCount = 0, maxCount = 5000, fingerprint = {{dmg=35.0,id="appliedenergestics2:item.ItemMultiMaterial"}}, raw_name = {"item.appliedenergestics2.itemmaterial.cell1kpart"}},
		{text = "Кость", buyPrice = 3000, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:bone"}}, raw_name = {"item.bone"}},
		{text = "Сахарный тростник", buyPrice = 15, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:reeds"}}, raw_name = {"ite.reeds"}},
		{text = "Капля мёда", buyPrice = 500, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="Forestry:honeyDrop"}}, raw_name = {"item.for.honeydrop.honey"}},
		{text = "Медвяная роса", buyPrice = 500, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="Forestry:honeydew"}}, raw_name = {"item.item.for.honeydew"}},
		{text = "Слизь", buyPrice = 5000, minCount = 0, maxCount = 5000, fingerprint = {{dmg=0.0,id="minecraft:slime_ball"}}, raw_name = {"item.slimeball"}},
		{text = "Слиток Мифрила", buyPrice = 250, minCount = 0, maxCount = 15000, fingerprint = {{dmg=70.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotmithril"}},
		{text = "Карта ускорения", buyPrice = 1500, minCount = 0, maxCount = 1500, fingerprint = {{dmg=30.0,id="appliedenergestics2:item.ItemMultiMatrial"}}, raw_name = {"item.appliedenergestics2.itemmaterial.cardspeed"}},
		{text = "Лазурит", buyPrice = 15, minCount = 0, maxCount = 15000, fingerprint = {{dmg=4.0,id="minecraft:dye"}}, raw_name = {"item.dye"}},
		{text = "Уголь", buyPrice = 15, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:coal"}}, raw_name = {"item.coal"}},
		{text = "Солн.Панель 2 уровень", buyPrice = 20000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="CompactSolars:CompactSolarBlock"}}, raw_name = {"tile.compactsolars:lv_block"}},
		{text = "Слиток Урана", buyPrice = 720, minCount = 0, maxCount = 50000, fingerprint = {{dmg=11.0,id="AdvancedSolarPanel:asp_crafting_items"}}, raw_name = {"itemuraningot"}},
		{text = "Изумрудная монета", sellPrice = 5000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="customnpc:NpcCoinEmerald"}}, raw_name = {"item.npccoinemerald"}},
		{text = "Золотая монета", sellPrice = 4000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="customnpc:NpcCoinGold"}}, raw_name = {"item.npccoingold"}},
		{text = "Железная монета", sellPrice = 2000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="customnpc:NpcCoinIron"}}, raw_name = {"item.npccoiniron"}},
		{text = "Каменная монета", sellPrice = 1000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="customnpc:NpcCoinStone"}}, raw_name = {"item.npccoinstone"}},
		{text = "Деревянная монета", sellPrice = 500, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="customnpc:NpcCoinWooden"}}, raw_name = {"item.npccoinwooden"}},
		{text = "МЭ Накопитель", buyPrice = 1000, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="appliedenergestics2:tile.BlockDrive"}}, raw_name = {"tile.appliedenergestics2.blockdrive"}},
		{text = "Блок создания", buyPrice = 1000, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="appliedenergestics2:tile.BlockCraftingUnit"}}, raw_name = {"tile.appliedenergestics2.blockcraftingunit"}},
		{text = "Осколок хаоса", buyPrice = 100000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="DraconicEvolution:chaousShard"}}, raw_name = {"item.draconicEvolution:chaousshard"}},
		{text = "Слиток никеля", buyPrice = 175, minCount = 0, maxCount = 20000, fingerprint = {{dmg=68.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotnickel"}},
		{text = "Пульсирующая сеть", buyPrice = 25000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=1.0,id="Forestry:craftingMaterial"}}, raw_name = {"item.craftingmaterial.pulsatingmesh"}},
		{text = "Небесный камень", buyPrice = 500, minCount = 0, maxCount = 5000, fingerprint = {{dmg=0.0,id="appliedenergestics2:BlockSkyStone"}}, raw_name = {"item.appliedenergestics2.blockskystone"}},
		{text = "Земля с травой", buyPrice = 30, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id="minecraft:grass"}}, raw_name = {"tile.grass"}},
		{text = "Земля", buyPrice = 15, minCount = 0, maxCount = 50000, fingerprint = {{dmg=0.0,id="minecraft:dirt"}}, raw_name = {"tile.dirt.deffault"}},
		{text = "Золотая руда", sellPrice = 100, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:gold_ore"}}, raw_name = {"tile.oregold"}},
		{text = "Железная руда", sellPrice = 100, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:item_ore"}}, raw_name = {"tile.oreiron"}},
		{text = "Свето камень", buyPrice = 420, minCount = 0, maxCount = 10000, fingerprint = {{dmg=0.0,id="minecraft:glowstone"}}, raw_name = {"tile.lightgem"}},
		{text = "Алмазный бур", buyPrice = 50000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=26.0,id="IC2:itemToolDDrill"}}, raw_name = {"ic2.itemtoolddrill"}},
		{text = "Латекс", buyPrice = 75, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="IC2:itemHarz"}}, raw_name = {"ic2.itemharz"}},
		{text = "Адский камень", buyPrice = 200, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:netherrack"}}, raw_name = {"tile.hellrock"}},
		{text = "Плоскость истребления", buyPrice = 1000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=300.0,id="appliedenergestics2:item.ItemMultiPart"}}, raw_name = {"item.appliedenergestics2:itempart.annihilationplane"}},
		{text = "Продвинутый высекатель", buyPrice = 5000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="ae2stuff:Inscriber"}}, raw_name = {"tile.ae2stuff:inscriber"}},
		{text = "Шина Импорта", buyPrice = 1000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=240.0,id="appliedenergestics2:item.ItemMultiPart"}}, raw_name = {"item.appliedenergestics2:itempart.importbus"}},
		{text = "Шина Экспорта", buyPrice = 1000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=260.0,id="appliedenergestics2:item.ItemMultiPart"}}, raw_name = {"item.appliedenergestics2:itempart.exportbus"}},
		{text = "Адский нарост", buyPrice = 500, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:nether_wart"}}, raw_name = {"item.netherstalkseed"}},
		{text = "МЭ Контролер", buyPrice = 1500, minCount = 0, maxCount = 1500, fingerprint = {{dmg=0.0,id="appliedenergestics2:tile.BlockController"}}, raw_name = {"appliedenergestics2.blockcontroller"}},
		{text = "Беспроводной соединитель", buyPrice = 8000, minCount = 0, maxCount = 1000, fingerprint = {{dmg=0.0,id="ae2stuff:Wireless"}}, raw_name = {"tile.ae2stuff.wireless"}},
		{text = "Шерсть", buyPrice = 5000, minCount = 0, maxCount = 10000, fingerprint = {{dmg=0.0,id="minecraft:wool"}}, raw_name = {"item.wool"}},
		{text = "Ядро Дракона", buyPrice = 75000, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconicCore"}}, raw_name = {"item.draconicevolution:draconiccore"}},
		{text = "Ядро Виверны", buyPrice = 2500000, minCount = 0, maxCount = 500, fingerprint = {{dmg=0.0,id="DraconicEvolution:wyvernCore"}}, raw_name = {"item.draconicevolution:wyverncore"}},
		{text = "Жемчуг Эндера", buyPrice = 6000, sellPrice = 4000, minCount = 0, maxCount = 5000, fingerprint = {{dmg=0.0,id="minecraft:ender_pearl"}}, raw_name = {"item.enderpearl"}},
		{text = "Ядро Дракона", buyPrice = 75000, minCount = 0, maxCount = 500, fingerprint = {{dmg=0.0,id="DraconicEvolution:DraconicCore"}}, raw_name = {"item.draconicevolution:draconiccore"}},
		{text = "Блок красного камня", sellPrice = 50, minCount = 0, maxCount = 10000, fingerprint = {{dmg=0.0,id="minecraft:redstone_block"}}, raw_name = {"redstone_block"}},
		{text = "Иридий", buyPrice = 30000, minCount = 0, maxCount = 10000, fingerprint = {{id="IC2:itemOreIridium",dmg=0.0}}, raw_name = {"ic2.itemoreiridium"}},
		{text = "Сера", buyPrice = 150, minCount = 0, maxCount = 10000, fingerprint = {{id="ThermalFoundation:material",dmg=16.0}}, raw_name = {"item.thermalfoundation.material.dustsulfur", "ic2.itemdustsulfur"}},
		{text = "Улучшение Ускоритель", buyPrice = 1200, minCount = 0, maxCount = 5000, fingerprint = {{dmg=0.0,id="IC2:upgradeModule"}}, raw_name = {"ic2.overclockerupgrade"}},
		{text = "Кварц", buyPrice = 140, minCount = 0, maxCount = 15000, fingerprint = {{dmg=0.0,id="minecraft:quartz"}}, raw_name = {"item.netherquartz"}},
		{text = "Укр. иридиевая пластина", buyPrice = 120000, minCount = 0, maxCount = 5000, fingerprint = {{id="IC2:itemPartIridium",dmg=0.0}}, raw_name = {"ic2.itempartiridium"}},
		{text = "Изумруд", buyPrice = 560, minCount = 0, maxCount = 5000, fingerprint = {{id="minecraft:emerald",dmg=0.0}}, raw_name = {"item.emerald"}},
		{text = "Череп Скелета-Иссушителя", buyPrice = 2000000, minCount = 0, needed = 128, maxCount = 500, fingerprint = {{dmg=1.0,id="minecraft:skull"}}, raw_name = {"item.skull.wither"}},
		{text = "Слиток закалённого железа", buyPrice = 520, minCount = 0, maxCount = 15000, fingerprint = {{id="ImmersiveEngineering:metal",dmg=7.0}, {dmg=4.0,id="Mekanism:Ingot"}}, raw_name = {"item.immersiveengineering.metal.ingotsteel"}},
		{text = "Выч. пресс для высекателя", buyPrice = 15000, minCount = 0, maxCount = 500, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=13.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.calcprocessorpress"}},
      		{text = "Инж. пресс для высекателя", buyPrice = 15000, minCount = 0, maxCount = 500, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=14.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.engprocessorpress"}},
        	{text = "Лог. пресс для высекателя", buyPrice = 15000, minCount = 0, maxCount = 500, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=15.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.logicprocessorpress"}},
        	{text = "Крем. пресс для высекателя", buyPrice = 15000, minCount = 0, maxCount = 500, fingerprint = {{id="appliedenergistics2:item.ItemMultiMaterial",dmg=19.0}}, raw_name = {"item.appliedenergistics2.itemmaterial.siliconpress"}},
        	{text = "Светопыль", buyPrice = 300, minCount = 0, maxCount = 15000, fingerprint = {{id="minecraft:glowstone_dust",dmg=0.0}}, raw_name = {"item.yellowdust"}},
		{text = "Красная пыль", buyPrice = 15, minCount = 0, maxCount = 15000, fingerprint = {{id="minecraft:redstone",dmg=0.0}}, raw_name = {"item.redstone"}},
		{text = "Алмаз", buyPrice = 450, minCount = 0, maxCount = 5000, fingerprint = {{dmg=0.0,id="minecraft:diamond"}}, raw_name = {"item.diamond"}},
		{text = "Слиток Свинца", buyPrice = 175, minCount = 0, maxCount = 15000,  fingerprint = {{dmg=5.0,id="IC2:itemIngot"}}, raw_name = {"ic2.itemingotlead"}},
		{text = "Слиток Платины", buyPrice = 385, minCount = 0, maxCount = 15000, fingerprint = {{dmg=69.0,id="ThermalFoundation:material"}}, raw_name = {"item.thermalfoundation.material.ingotplatinum"}},
		{text = "Слиток Серебра", buyPrice = 280, minCount = 0, maxCount = 15000,  fingerprint = {{dmg=6.0,id="IC2:itemIngot", {dmg=66.0,id="ThermalFoundation:material"}}}, raw_name ={"ic2.itemingotsilver", "item.thermalfoundation.material.ingotsilver"}},
		{text = "Слиток Золота", buyPrice = 75, minCount = 0, maxCount = 15000,  fingerprint = {{dmg=0.0,id="minecraft:gold_ingot"}}, raw_name = {"item.ingotgold"}},
		{text = "Слиток Железа", buyPrice = 50, minCount = 0, maxCount = 15000,  fingerprint = {{dmg=0.0,id="minecraft:iron_ingot"}}, raw_name = {"item.ingotiron"}},
		{text = "Резина", buyPrice = 25, minCount = 0, maxCount = 15000,  fingerprint = {{dmg=0.0,id="IC2:itemRubber"}}, raw_name = {"item.itemrubber"}},
		{text = "10.000$(SkillCoin)", buyPrice = 10000, sellPrice = 10000, minCount = 0, maxCount = 500, fingerprint = {{dmg=0.0,id="customnpcs:npcCoinBronze"}}, raw_name = {"item.npccoinbronze"}},
		{text = "100.000$(SkillCoin)", buyPrice = 100000, sellPrice = 100000, minCount = 0, maxCount = 500, fingerprint = {{dmg=0.0,id="customnpcs:npcCoinDiamond"}}, raw_name = {"item.npccoindiamond"}},
		{text = "Горячий кофе", buyPrice = 850, minCount = 0, maxCount = 1310720, fingerprint = {{dmg=1.0,id="IC2:itemMugCoffee"}}, raw_name = {"ic2.itemmugcoffee_1"}},
		{text = "Дуб", sellPrice = 50, minCount = 0, maxCount = 10000, fingerprint = {{dmg=0.0,id="minecraft:log"}}, raw_name = {"tile.log.oak"}},
		{text = "Слиток Дракония", buyPrice = 700, minCount = 0, maxCount = 10000, fingerprint = {{dmg=0.0,id="DraconicEvolution:draconiumIngot"}}, raw_name = {"item.draconicevolution:draconiumingot"}},
		{text = "Урановая руда", buyPrice = 1440, minCount = 0, maxCount = 10000, fingerprint = {{dmg=0.0,id="IC2:blockOreUran"}}, raw_name = {"ic2.blockoreuran"}},
    },

    ore = {
	{text="",ratio=2,raw_name={""},fingerprint={{dmg=0.0,id=""}}},
	{text="",ratio=2,raw_name={""},fingerprint={{dmg=0.0,id=""}}},
	{text="Мифриловая руда",ratio=2,raw_name={"tile.thermalfoundation.ore.mithril.name"},fingerprint={{dmg=70.0,id="ThermalFoundation:material"}}},
	{text="Платиновая руда",ratio=2,raw_name={"tile.thermalfoundation.ore.platinum.name"},fingerprint={{dmg=69.0,id="ThermalFoundation:material"}}},
        {text="Железная руда",ratio=2,raw_name={"tile.oreiron"},fingerprint={{dmg=0.0,id="minecraft:iron_ingot"}}},
        {text="Золотая руда",ratio=2,raw_name={"tile.oregold"},fingerprint={{dmg=0.0,id="minecraft:gold_ingot"}}},
        {text="Медная руда",ratio=2,raw_name={"tile.thermalfoundation.ore.copper.name","ic2.blockorecopper"},fingerprint={{dmg=64.0,id="ThermalFoundation:material"},{dmg=0.0,id="IC2:itemIngot"},{dmg=0.0,id="ImmersiveEngineering:metal"},{dmg=5.0,id="Mekanism:Ingot"}}},
        {text="Оловянная руда",ratio=2,raw_name={"tile.thermalfoundation.ore.tin.name","ic2.blockoretin"},fingerprint={{dmg=6.0,id="Mekanism:Ingot"},{dmg=65.0,id="ThermalFoundation:material"},{dmg=1.0,id="IC2:itemIngot"}}},
        {text="Серебряная руда",ratio=2,raw_name={"tile.thermalfoundation.ore.silver.name"},fingerprint={{dmg=66.0,id="ThermalFoundation:material"},{dmg=6.0,id="IC2:itemIngot"}}},
    },

    food = {{dmg=0.0, id="minecraft:melon"}}
}
